# Generated by Django 5.1.5 on 2025-01-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('cashier', 'Cashier'), ('stock_keeper', 'Stock Keeper'), ('wholesale_client', 'Wholesale Client'), ('sales_agent', 'Sales Agent')], max_length=30),
        ),
    ]
