# Generated by Django 5.1.5 on 2025-02-21 18:53
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_blacklistedtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlacklistedToken',
            new_name='RevokedToken',
        ),
    ]
