# Generated by Django 5.1.5 on 2025-01-27 13:28
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_product_tax_delete_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='subcategory',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='stock.subcategory',
            ),
        ),
    ]
