# Generated by Django 5.1.5 on 2025-01-30 18:45
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
    ]
