# Generated by Django 5.1.5 on 2025-02-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_stock_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at']},
        ),
    ]
