# Generated by Django 5.1.5 on 2025-02-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_product_options_alter_stock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
