# Generated by Django 5.1.5 on 2025-02-02 17:44
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_product_options_alter_stock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='image',
            field=models.ImageField(
                blank=True, null=True, upload_to='products/'
            ),
        ),
    ]
