# Generated by Django 5.1.5 on 2025-02-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_stockmovement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
