# Generated by Django 5.1.6 on 2025-06-12 17:09
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_rename_update_by_category_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='updated_by',
        ),
    ]
