# Generated by Django 5.1.5 on 2025-08-04 19:12
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_is_read_notification_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
    ]
