# Generated by Django 5.1.5 on 2025-05-21 13:42
from __future__ import annotations

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_passwordresettoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passwordresettoken",
            name="user",
        ),
        migrations.DeleteModel(
            name="RevokedToken",
        ),
        migrations.AddField(
            model_name="user",
            name="last_password_reset",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="PasswordResetToken",
        ),
    ]
