# Generated by Django 5.1.5 on 2025-05-21 17:15
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jti", models.UUIDField(unique=True)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
    ]
