# Generated by Django 5.1.6 on 2025-06-11 14:58
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_revokedtoken_delete_blacklistedaccesstoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RevokedToken',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_password_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
