# Generated by Django 5.1.5 on 2025-08-04 19:12
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_delete_revokedtoken_alter_user_last_password_reset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={
                'ordering': ['username'],
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
