# Generated by Django 5.1.5 on 2025-03-13 18:19
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_alter_inventoryreport_created_at"),
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryreport",
            name="stocks",
            field=models.ManyToManyField(to="stock.stock"),
        ),
    ]
