# Generated by Django 5.1.5 on 2025-04-08 14:19
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_inventoryreport_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicearchive',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
