# Generated by Django 5.1.5 on 2025-04-16 10:50
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_invoicearchive_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryreport',
            name='date_range',
        ),
        migrations.AddField(
            model_name='inventoryreport',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryreport',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryreport',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryreport',
            name='report',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='inventory_report',
                to='reports.report',
            ),
        ),
        migrations.AddField(
            model_name='inventoryreport',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='report',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sales_report',
                to='reports.report',
            ),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
