# Generated by Django 5.1.5 on 2025-04-25 12:10
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_alter_salesreport_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceline",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="line_total",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="unit_price",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
