# Generated by Django 5.1.6 on 2025-06-12 17:09
from __future__ import annotations

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_invoice_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                (
                    'expense_type',
                    models.CharField(
                        choices=[
                            ('REPLENISHMENT', 'Replenishment'),
                            ('MISCELLANEOUS', 'Miscellaneous'),
                            ('ELECTRICITY', 'Electricity Bill'),
                            ('WATER', 'Water Bill'),
                            ('SALARY', 'Salary'),
                            ('EXTRA', 'Extra'),
                            ('MAINTENANCE', 'Maintenance'),
                            ('TAX', 'Tax'),
                            ('RENT', 'Rent'),
                        ],
                        max_length=20,
                    ),
                ),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='expenses',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-created_at'],
            },
        ),
    ]
