# Generated by Django 5.1.6 on 2025-06-12 17:11
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0011_expense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
        ),
    ]
