# Generated by Django 5.1.5 on 2025-06-13 07:24
from __future__ import annotations

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_rename_user_expense_created_by_expense_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasure',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'balance',
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
                ),
                (
                    'total_sales',
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
                ),
                (
                    'total_expenses',
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
                ),
                (
                    'total_credit',
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
                ),
                (
                    'outstanding_debt',
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
                ),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('history', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Treasure',
                'verbose_name_plural': 'Treasures',
            },
        ),
    ]
