# Generated by Django 5.1.5 on 2025-08-04 19:12
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_treasure'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expense',
            table='expenses',
        ),
        migrations.AlterModelTable(
            name='inventoryreport',
            table='inventory_reports',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='invoices',
        ),
        migrations.AlterModelTable(
            name='invoicearchive',
            table='archived_invoices',
        ),
        migrations.AlterModelTable(
            name='invoicearchiveline',
            table='archived_invoice_lines',
        ),
        migrations.AlterModelTable(
            name='invoiceline',
            table='invoice_lines',
        ),
        migrations.AlterModelTable(
            name='report',
            table='reports',
        ),
        migrations.AlterModelTable(
            name='salesreport',
            table='sales_reports',
        ),
        migrations.AlterModelTable(
            name='treasure',
            table='treasure',
        ),
    ]
