# Generated by Django 5.1.5 on 2025-02-02 16:17
from __future__ import annotations

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0006_alter_product_options_alter_stock_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('expired_products', models.PositiveIntegerField(default=0)),
                ('low_stock_products', models.PositiveIntegerField(default=0)),
                ('date_range', models.CharField(default=None, max_length=255)),
                (
                    'generated_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='inventory_reports',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Inventory Report',
                'verbose_name_plural': 'Inventory Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'number',
                    models.PositiveIntegerField(editable=False, unique=True),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'client_name',
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('COMPLETED', 'Completed'),
                            ('CANCELLED', 'Cancelled'),
                            ('CREDIT', 'Credit'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'total',
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10
                    ),
                ),
                (
                    'tax',
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=5
                    ),
                ),
                ('reason', models.TextField(blank=True, null=True)),
                (
                    'advance_paid',
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10
                    ),
                ),
                (
                    '_remaining_amount',
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10
                    ),
                ),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_credit_settled', models.BooleanField(default=False)),
                (
                    'cashier',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='invoices',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('quantity', models.PositiveIntegerField()),
                (
                    'unit_price',
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    'discount',
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=5
                    ),
                ),
                (
                    'line_total',
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    'invoice',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lines',
                        to='reports.invoice',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invoice_lines',
                        to='stock.product',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Invoice Line',
                'verbose_name_plural': 'Invoice Lines',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'notification_type',
                    models.CharField(
                        choices=[
                            ('CRITICAL_STOCK', 'Critical Stock'),
                            ('EXPIRED', 'Expired Product'),
                            ('NEAR_EXPIRY', 'Near Expiry'),
                        ],
                        default='CRITICAL_STOCK',
                        max_length=20,
                    ),
                ),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notifications',
                        to='stock.product',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notifications',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('inventory', 'Inventory'),
                            ('sales', 'Sales'),
                            ('returns', 'Returns'),
                            ('expired', 'Expired Products'),
                        ],
                        max_length=20,
                    ),
                ),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                (
                    'file_path',
                    models.FileField(
                        blank=True, null=True, upload_to='reports/'
                    ),
                ),
                ('description', models.TextField(blank=True, null=True)),
                (
                    'generated_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='reports',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'date',
                    models.DateField(
                        default=django.utils.timezone.now, unique=True
                    ),
                ),
                (
                    'total_sales',
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10
                    ),
                ),
                ('total_invoices', models.PositiveIntegerField(default=0)),
                (
                    'generated_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='sales_reports',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Sales Report',
                'verbose_name_plural': 'Sales Reports',
                'ordering': ['-date'],
            },
        ),
    ]
