# Generated by Django 5.1.5 on 2025-03-13 17:46
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
