# Generated by Django 5.1.5 on 2025-01-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='date',
            new_name='created_at',
        ),
    ]
