# Generated by Django 5.1.5 on 2025-02-03 20:02
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_inventoryreport_id_alter_invoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
