# Generated by Django 5.1.5 on 2025-01-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_invoice_options_rename_date_invoice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='total_invoices',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
