# Generated by Django 5.1.5 on 2025-02-06 11:48
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_invoice_refund_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
