# Generated by Django 5.1.5 on 2025-01-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_salesreport_total_invoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='total_invoices',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
