# Generated by Django 5.1.5 on 2025-02-14 14:47
from __future__ import annotations

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceArchive',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('number', models.PositiveIntegerField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'client_name',
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('COMPLETED', 'Completed'),
                            ('CANCELLED', 'Cancelled'),
                            ('CREDIT', 'Credit'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'total',
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    'tax',
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ('reason', models.TextField(blank=True, null=True)),
                (
                    'refund_amount',
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    'advance_paid',
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    '_remaining_amount',
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_credit_settled', models.BooleanField(default=False)),
                (
                    'cashier',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='archived_invoices',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Archived Invoice',
                'verbose_name_plural': 'Archived Invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
