# Generated by Django 5.1.5 on 2025-01-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_salesreport_total_invoices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='paid_amount',
            new_name='advance_paid',
        ),
        migrations.AddField(
            model_name='invoice',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('CREDIT', 'Credit')], default='PENDING', max_length=20),
        ),
    ]
