# Generated by Django 5.1.5 on 2025-02-15 17:34
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_invoicearchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicearchive',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoicearchive',
            name='invoice_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
