# Generated by Django 5.1.5 on 2025-01-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_rename_paid_amount_invoice_advance_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreport',
            name='date_range',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
