# Generated by Django 5.1.5 on 2025-02-15 17:42
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_invoicearchive_invoice_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicearchive',
            name='invoice_number',
        ),
    ]
