# Generated by Django 5.1.5 on 2025-01-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_inventoryreport_date_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryreport',
            old_name='date',
            new_name='created_at',
        ),
    ]
