# Generated by Django 5.1.5 on 2025-01-29 21:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_rename_date_inventoryreport_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True),
        ),
    ]
