# Generated by Django 5.1.5 on 2025-02-15 19:13
from __future__ import annotations

import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_remove_invoicearchive_invoice_number'),
        ('stock', '0009_category_created_at_subcategory_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceArchiveLine',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    'discount',
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    'invoice',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lines',
                        to='reports.invoicearchive',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='archived_invoice_lines',
                        to='stock.product',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Archived Invoice Line',
                'verbose_name_plural': 'Archived Invoice Lines',
            },
        ),
    ]
