# Generated by Django 5.1.5 on 2025-01-30 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_salesreport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
