# Generated by Django 5.1.5 on 2025-01-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_salesreport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
