# Generated by Django 5.1.5 on 2025-01-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_invoice_remaining_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='remaining_amount',
        ),
    ]
