# Generated by Django 5.1.5 on 2025-02-01 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_invoice__remaining_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inventory Report', 'verbose_name_plural': 'Inventory Reports'},
        ),
        migrations.AlterModelOptions(
            name='salesreport',
            options={'ordering': ['-date'], 'verbose_name': 'Sales Report', 'verbose_name_plural': 'Sales Reports'},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='resolved',
            new_name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CRITICAL_STOCK', 'Critical Stock'), ('EXPIRED', 'Expired Product'), ('NEAR_EXPIRY', 'Near Expiry')], default='CRITICAL_STOCK', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
