# Generated by Django 5.1.5 on 2025-06-04 14:10
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_rename_image_url_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
