# Generated by Django 5.1.6 on 2025-06-12 11:03
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_stockmovement_created_by_category_update_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='update_by',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='update_by',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='update_by',
            new_name='updated_by',
        ),
    ]
