# Generated by Django 5.1.5 on 2025-08-05 17:39
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='barcode_url',
            new_name='barcode_image_url',
        ),
    ]
