
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: stockmanagement_local
      POSTGRES_USER: retailpulse
      POSTGRES_PASSWORD: retailpulse
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - backend

  celery:
    build: .
    command: celery -A retailpulse worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - backend

  celery-beat:
    build: .
    command: celery -A retailpulse beat --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - celery
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
