
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: stockmanagement_local
      POSTGRES_USER: stockmanagement
      POSTGRES_PASSWORD: stockmanagement
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env  # Charge les variables d'environnement depuis .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
