from __future__ import annotations

import io
import logging
from datetime import datetime
from datetime import time
from datetime import timedelta
from decimal import Decimal

from django.db import transaction
from django.db.models import F
from django.db.models import Sum
from django.template.loader import render_to_string
from django.utils import timezone
from reports.models import Expense
from reports.models import InventoryReport
from reports.models import Invoice
from reports.models import InvoiceLine
from reports.models import Report
from reports.models import SalesReport
from reports.service.entities import ServiceResponse
from stock.models import Product
from stock.models import Stock
from weasyprint import HTML

logger = logging.getLogger(__name__)


class GenerateReportService:

    @staticmethod
    def get_date_range(start_date=None, end_date=None):
        if start_date and end_date:
            if isinstance(start_date, str):
                start_date = datetime.fromisoformat(start_date).date()
            if isinstance(end_date, str):
                end_date = datetime.fromisoformat(end_date).date()
            start = datetime.combine(start_date, time.min)
            end = datetime.combine(end_date, time.max)
        else:
            today = timezone.now().date()
            start = datetime.combine(today, time.min)
            end = datetime.combine(today, time.max)

        return timezone.make_aware(start), timezone.make_aware(end)

    @staticmethod
    def decimal_to_json_serializable(obj):
        import decimal
        import datetime

        if isinstance(obj, decimal.Decimal):
            return float(obj)
        elif isinstance(obj, datetime.datetime):
            return obj.isoformat()
        elif isinstance(obj, datetime.date):
            return obj.isoformat()
        elif isinstance(obj, dict):
            return {k: GenerateReportService.decimal_to_json_serializable(v)
                    for k, v in obj.items()}
        elif isinstance(obj, list):
            return [GenerateReportService.decimal_to_json_serializable(i) for i in obj]
        return obj

    @staticmethod
    def generate_report(
            report_type: str,
            user,
            start_date: str = None,
            end_date: str = None,
    ) -> ServiceResponse:
        try:
            # Déterminer la plage de dates
            start_date, end_date = GenerateReportService.get_date_range(
                start_date, end_date
            )
            if report_type not in dict(Report.REPORT_TYPE_CHOICES):
                return ServiceResponse(success=False, error='Invalid report type.')

            report_data = GenerateReportService._get_report_data(
                report_type, start_date, end_date
            )
            report_data = GenerateReportService.decimal_to_json_serializable(report_data)
            report_data['report_type'] = report_type
            report_data['generated_by'] = user.username
            report_data['created_at'] = timezone.now().isoformat()
            report_data['start_date'] = start_date.isoformat()
            report_data['end_date'] = end_date.isoformat()
            print('report data', report_data)

            with transaction.atomic():
                current_time = timezone.now()
                report = Report.objects.create(
                    type=report_type,
                    generated_by=user,
                    description=f"{report_type.capitalize()} report generated by {user}",
                    generated_at=current_time
                )

                if report_type == 'inventory':
                    inventory_report = InventoryReport.objects.create(
                        report=report,
                        generated_by=user,
                        start_date=start_date,
                        end_date=end_date,
                        total_products=report_data['total_products'],
                        expired_products=report_data['expired_products'],
                        low_stock_products=report_data['low_stock_products'],
                        data=report_data,
                    )
                    inventory_report.stocks.set(Stock.objects.filter(
                        created_at__date__range=[start_date, end_date])
                    )

                elif report_type == 'sales':

                    total_completed_revenue = report_data.get('total_completed_revenue', 0)
                    total_advance_paid = report_data.get('total_advance_paid', 0)
                    total_completed_sales = report_data.get('total_completed_sales', 0)
                    total_credit_sales = report_data.get('total_credit_sales', 0)
                    total_sales = total_completed_revenue + total_advance_paid
                    total_invoices = total_completed_sales + total_credit_sales

                    sales_report, created = SalesReport.objects.get_or_create(
                        date=current_time.date(),
                        defaults={
                            'report': report,
                            'generated_by': user,
                            'start_date': start_date,
                            'end_date': end_date,
                            'total_sales': total_sales,
                            'total_invoices': total_invoices,
                            'data': report_data,
                        }
                    )
                    if not created:
                        sales_report.report = report
                        sales_report.generated_by = user
                        sales_report.start_date = start_date
                        sales_report.end_date = end_date
                        sales_report.total_sales = total_sales
                        sales_report.total_invoices = total_invoices
                        sales_report.data = report_data
                        sales_report.created_at = current_time
                        sales_report.save()

            return ServiceResponse(
                success=True, data={'report_id': report.id, 'report_data': report_data}
            )
        except Exception as e:
            return ServiceResponse(success=False, error=str(e))

    @staticmethod
    def _get_report_data(
            report_type: str, start_date=None, end_date=None
    ):
        if report_type == 'inventory':
            return GenerateReportService._generate_inventory_data(start_date, end_date)
        elif report_type == 'sales':
            sales_data_response = GenerateReportService._generate_sales_data(
                start_date, end_date
            )
            return sales_data_response.data if sales_data_response.success else {}
        return {}

    @staticmethod
    def _generate_inventory_data(start_date=None, end_date=None):
        now = timezone.now()
        soon = now + timedelta(days=14)

        if start_date and end_date:
            products = Product.objects.filter(
                created_at__date__range=[start_date, end_date]
            ).select_related('category', 'subcategory')
        else:
            products = Product.objects.all().select_related('category', 'subcategory')

        near_expiry = products.filter(
            expiry_date__range=(now, soon), is_expired=False
        )

        product_list = []
        for product in products:
            product_list.append({
                'name': product.name,
                'category': product.category.name if product.category else None,
                'subcategory': product.subcategory.name if product.subcategory else None,
                'quantity': product.quantity,
                'min_quantity': product.min_quantity,
                'is_expired': product.is_expired,
                'expiry_date': product.expiry_date.isoformat()
                if product.expiry_date else None,
                'is_near_expiry': product in near_expiry,
                'is_critical': product.quantity < product.min_quantity,
                'created_at': product.created_at.isoformat() if product.created_at else None,
            })

        return {
            'total_products': products.count(),
            'expired_products': products.filter(is_expired=True).count(),
            'near_expiry_count': near_expiry.count(),
            'low_stock_products': products.filter(quantity__lt=F('min_quantity')).count(),
            'product_list': product_list,
        }

    @staticmethod
    def _generate_sales_data(
            start_date=None, end_date=None
    ):
        try:
            completed_invoices = Invoice.objects.filter(
                status='COMPLETED',
                created_at__date__range=[start_date, end_date]
            )
            credit_invoices = Invoice.objects.filter(
                status='CREDIT',
                created_at__date__range=[start_date, end_date]
            )

            invoice_ids = list(completed_invoices.values_list('id', flat=True)) + list(
                credit_invoices.values_list('id', flat=True))

            completed_revenue = InvoiceLine.objects.filter(
                invoice__in=completed_invoices
            ).aggregate(total=Sum('line_total'))['total'] or 0

            total_credit_revenue = InvoiceLine.objects.filter(
                invoice__in=credit_invoices
            ).aggregate(total=Sum('line_total'))['total'] or 0

            total_advance_paid = credit_invoices.aggregate(
                total=Sum('advance_paid'))['total'] or 0
            total_remaining_amount = credit_invoices.aggregate(
                total=Sum('_remaining_amount'))['total'] or 0

            credit_profit = InvoiceLine.objects.filter(
                invoice__in=credit_invoices
            ).aggregate(
                total=Sum((F('unit_price') - F('product__purchase_price')) * F('quantity'))
            )['total'] or 0

            profit = InvoiceLine.objects.filter(
                invoice__in=completed_invoices
            ).aggregate(
                total=Sum((F('unit_price') - F('product__purchase_price')) * F('quantity'))
            )['total'] or 0
            discount = InvoiceLine.objects.filter(
                invoice__in=invoice_ids
            ).aggregate(discount=Sum('discount'))['discount'] or 0

            sold_products = list(
                InvoiceLine.objects.filter(invoice_id__in=invoice_ids)
                .values('product__name', 'unit_price')
                .annotate(
                    total_quantity=Sum('quantity'),
                    total_revenue=Sum('line_total')
                ).order_by('-total_quantity')
            )

            total_expenses = Expense.objects.filter(
                created_at__date__range=(start_date, end_date)
            ).aggregate(total=Sum('amount'))['total'] or Decimal('0.00')

            total_purchase = InvoiceLine.objects.filter(
                invoice__in=invoice_ids
            ).aggregate(
                total_purchase=Sum(F('product__purchase_price') * F('quantity'))
            )['total_purchase'] or Decimal('0.00')

            total_revenue = completed_revenue + total_credit_revenue
            gross_profit = (profit + credit_profit)
            net_profit_before_expenses = gross_profit - discount
            net_profit = net_profit_before_expenses - total_expenses

            expense_details = [
                {
                    'type': e.expense_type,
                    'amount': float(e.amount),
                    'reason': e.reason,
                    'date': e.created_at.isoformat()
                }
                for e in Expense.objects.filter(
                    created_at__date__range=(start_date, end_date)
                )
                ]

            return ServiceResponse(success=True, data={
                'total_completed_sales': completed_invoices.count(),
                'total_completed_revenue': completed_revenue,
                'total_credit_sales': credit_invoices.count(),
                'total_credit_revenue': total_credit_revenue,
                'total_revenue': total_revenue,
                'total_purchase': total_purchase,
                'total_discount': discount,
                'total_expenses': total_expenses,
                'total_profit_brute': gross_profit,
                'profit_expenses_discount': net_profit_before_expenses,
                'total_profit_net': net_profit,
                'total_advance_paid': total_advance_paid,
                'money_outstanding': total_remaining_amount,
                'products_sold': sold_products,
                'expense_details': expense_details
            })

        except Exception as e:
            logger.error(f'Error generating sales data: {e}')
            return ServiceResponse(success=False, error=str(e))

    @staticmethod
    def download_report(report_id):
        try:
            report = Report.objects.get(id=report_id)
            report_type = report.type
            print('report_type', report_type)
            if report_type == 'inventory':
                specific = InventoryReport.objects.get(report_id=report.id)
                print('inventory', specific)
            elif report_type == 'sales':
                specific = SalesReport.objects.get(report_id=report.id)
                print('sales', specific)

            else:
                return ServiceResponse(success=False, error='Unsupported report type.')

            html_string = render_to_string(
                f'{report_type}_report_template.html',
                {'data': specific.data}
            )

            buffer = io.BytesIO()
            HTML(string=html_string).write_pdf(buffer)
            buffer.seek(0)
            return ServiceResponse(success=True, data={
                'pdf_file': buffer,
                'filename': f"{report_type}_report_{datetime.now().date()}.pdf"
            })

        except Report.DoesNotExist:
            return ServiceResponse(success=False, error='Report not found')
        except Exception as e:
            return ServiceResponse(success=False, error=str(e))
