# Generated by Django 5.1.5 on 2025-03-19 19:30
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(
                choices=[
                    ('UNREAD', 'Unread'),
                    ('READ', 'Read'),
                    ('ARCHIVED', 'Archived'),
                ],
                default='UNREAD',
                max_length=20,
            ),
        ),
    ]
