# Generated by Django 5.2.8 on 2025-11-11 10:54

import uuid
from decimal import Decimal

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetailPulseUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Deprecated: Use name instead",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="User's display name (not unique)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Unique phone number for login (required if email is not provided)",
                        max_length=30,
                        null=True,
                        unique=True,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("avatar_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("email_password", "Email/Password"),
                            ("google_oauth", "Google OAuth"),
                            ("phone_otp", "Phone OTP"),
                        ],
                        default="email_password",
                        help_text="Authentication method used to create/login to account",
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "OWNER"),
                            ("manager", "MANAGER"),
                            ("cashier", "CASHIER"),
                            ("stock_keeper", "STOCK_KEEPER"),
                            ("delivery", "DELIVERY"),
                            ("customer", "CUSTOMER"),
                            ("wholesaler", "WHOLESALER"),
                            ("partner", "PARTNER"),
                        ],
                        default="customer",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "RetailPulse User",
                "verbose_name_plural": "RetailPulse Users",
                "db_table": "retailpulse_users",
                "ordering": ["name"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("unique_name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("qr_code_url", models.URLField(blank=True, max_length=500, null=True)),
                ("logo_url", models.URLField(blank=True, max_length=500, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        db_column="owner_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_businesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business",
                "verbose_name_plural": "Businesses",
                "db_table": "businesses",
            },
        ),
        migrations.CreateModel(
            name="BusinessMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("role", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="persistence_models.business",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Member",
                "verbose_name_plural": "Business Members",
                "db_table": "business_members",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="persistence_models.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=30, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "loyalty_points",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15),
                ),
                (
                    "total_purchases",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15),
                ),
                (
                    "business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="persistence_models.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "customers",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("device_id", models.CharField(max_length=255, unique=True)),
                ("device_name", models.CharField(blank=True, max_length=255, null=True)),
                ("device_type", models.CharField(blank=True, max_length=50, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "db_table": "devices",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("REPLENISHMENT", "Replenishment"),
                            ("MISCELLANEOUS", "Miscellaneous"),
                            ("ELECTRICITY", "Electricity Bill"),
                            ("WATER", "Water Bill"),
                            ("SALARY", "Salary"),
                            ("EXTRA", "Extra"),
                            ("MAINTENANCE", "Maintenance"),
                            ("TAX", "Tax"),
                            ("RENT", "Rent"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("reason", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="persistence_models.business",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "db_table": "expenses",
            },
        ),
        migrations.CreateModel(
            name="FinancialSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15),
                ),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15),
                ),
                (
                    "total_salaries",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15),
                ),
                (
                    "net_profit",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_summaries",
                        to="persistence_models.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Summary",
                "verbose_name_plural": "Financial Summaries",
                "db_table": "financial_summaries",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("number", models.PositiveIntegerField()),
                ("customer_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("CREDIT", "Credit"),
                            ("PENDING", "Pending"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15),
                ),
                (
                    "advance_paid",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("mobile_money", "Mobile Money"),
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("credit", "Credit"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("is_credit_settled", models.BooleanField(default=False)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="persistence_models.business",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="persistence_models.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "db_table": "invoices",
            },
        ),
        migrations.CreateModel(
            name="CustomerPurchaseHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("purchase_date", models.DateTimeField()),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_purchases",
                        to="persistence_models.business",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_history",
                        to="persistence_models.customer",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_purchase_history",
                        to="persistence_models.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Purchase History",
                "verbose_name_plural": "Customer Purchase Histories",
                "db_table": "customer_purchase_history",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("CRITICAL_STOCK", "Critical Stock"),
                            ("EXPIRED", "Expired Product"),
                            ("NEAR_EXPIRY", "Near Expiry"),
                            ("ORDER", "Order"),
                            ("MEETING", "Meeting"),
                            ("SYSTEM", "System"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("UNREAD", "Unread"), ("READ", "Read"), ("ARCHIVED", "Archived")],
                        default="UNREAD",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("related_entity_type", models.CharField(blank=True, max_length=50, null=True)),
                ("related_entity_id", models.UUIDField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="persistence_models.business",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("order_number", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("mobile_money", "Mobile Money"),
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("shipping_address", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="persistence_models.business",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="persistence_models.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("shipping_address", models.TextField()),
                ("estimated_delivery_time", models.DateTimeField(blank=True, null=True)),
                ("actual_delivery_time", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="persistence_models.business",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="persistence_models.customer",
                    ),
                ),
                (
                    "delivery_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="persistence_models.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery",
                "verbose_name_plural": "Deliveries",
                "db_table": "deliveries",
            },
        ),
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, db_index=True, max_length=30, null=True),
                ),
                ("otp_code", models.CharField(max_length=6)),
                (
                    "otp_type",
                    models.CharField(choices=[("email", "Email"), ("sms", "SMS")], max_length=10),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("signup", "Signup"),
                            ("login", "Login"),
                            ("password_reset", "Password Reset"),
                            ("email_verification", "Email Verification"),
                            ("phone_verification", "Phone Verification"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, help_text="OTP expires 10 minutes after creation"
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.IntegerField(default=0)),
                (
                    "max_attempts",
                    models.IntegerField(
                        default=3, help_text="Maximum 3 verification attempts allowed"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP",
                "verbose_name_plural": "OTPs",
                "db_table": "otps",
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, db_index=True, max_length=30, null=True),
                ),
                ("token", models.CharField(db_index=True, max_length=255, unique=True)),
                ("code", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "reset_type",
                    models.CharField(choices=[("email", "Email"), ("sms", "SMS")], max_length=10),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset Token",
                "verbose_name_plural": "Password Reset Tokens",
                "db_table": "password_reset_tokens",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("barcode", models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ("barcode_image_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("min_quantity", models.PositiveIntegerField(default=10)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("is_expired", models.BooleanField(default=False)),
                ("on_promotion", models.BooleanField(default=False)),
                ("promotion_start_date", models.DateTimeField(blank=True, null=True)),
                ("promotion_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "promo_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="persistence_models.business",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="persistence_models.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="persistence_models.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="persistence_models.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
                "db_table": "order_items",
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="persistence_models.invoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_lines",
                        to="persistence_models.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Line",
                "verbose_name_plural": "Invoice Lines",
                "db_table": "invoice_lines",
            },
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("token", models.TextField(unique=True)),
                ("device_id", models.CharField(blank=True, max_length=255, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Refresh Token",
                "verbose_name_plural": "Refresh Tokens",
                "db_table": "refresh_tokens",
            },
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "payment_frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15),
                ),
                (
                    "bonuses",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15),
                ),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salaries",
                        to="persistence_models.business",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary",
                "verbose_name_plural": "Salaries",
                "db_table": "salaries",
            },
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("payment_date", models.DateTimeField()),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "deductions",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15),
                ),
                (
                    "bonuses",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payrolls",
                        to="persistence_models.business",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payrolls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "salary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payrolls",
                        to="persistence_models.salary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll",
                "verbose_name_plural": "Payrolls",
                "db_table": "payrolls",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("device_id", models.CharField(blank=True, max_length=255, null=True)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "db_table": "sessions",
                "ordering": ["-start_time"],
                "get_latest_by": "start_time",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("ENTRY", "Entry"),
                            ("EXIT", "Exit"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="persistence_models.business",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="persistence_models.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Movement",
                "verbose_name_plural": "Stock Movements",
                "db_table": "stock_movements",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="persistence_models.business",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="persistence_models.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_subcategories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SubCategory",
                "verbose_name_plural": "SubCategories",
                "db_table": "subcategories",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="persistence_models.subcategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="retailpulseuser",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("email__isnull", False), ("phone_number__isnull", False), _connector="OR"
                ),
                name="user_must_have_email_or_phone",
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(fields=["owner"], name="businesses_owner_i_1d3ff5_idx"),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(fields=["unique_name"], name="businesses_unique__7fc8f5_idx"),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(fields=["is_active"], name="businesses_is_acti_8eca54_idx"),
        ),
        migrations.AddIndex(
            model_name="businessmember",
            index=models.Index(
                fields=["business", "is_active"], name="business_me_busines_6792bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessmember",
            index=models.Index(fields=["user"], name="business_me_user_id_4053c6_idx"),
        ),
        migrations.AddIndex(
            model_name="businessmember",
            index=models.Index(fields=["role"], name="business_me_role_f36b91_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="businessmember",
            unique_together={("business", "user")},
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["business", "name"], name="categories_busines_11ea6f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("business", "name")},
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["business", "name"], name="customers_busines_813b1f_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="customers_email_92e882_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["phone_number"], name="customers_phone_n_7d2329_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["user", "device_id"], name="devices_user_id_0189e2_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["device_id"], name="devices_device__c4b5e4_idx"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["business", "-updated_at"], name="expenses_busines_b29107_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["expense_type"], name="expenses_expense_272666_idx"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["is_approved"], name="expenses_is_appr_314b58_idx"),
        ),
        migrations.AddIndex(
            model_name="financialsummary",
            index=models.Index(
                fields=["business", "period_start", "period_end"],
                name="financial_s_busines_73ed52_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["business", "-updated_at"], name="invoices_busines_805232_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="invoices_status_07776b_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["customer"], name="invoices_custome_ba8289_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("business", "number")},
        ),
        migrations.AddIndex(
            model_name="customerpurchasehistory",
            index=models.Index(
                fields=["customer", "-purchase_date"], name="customer_pu_custome_0eb27d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerpurchasehistory",
            index=models.Index(
                fields=["business", "-purchase_date"], name="customer_pu_busines_3e9ef3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "-updated_at"], name="notificatio_user_id_ee176c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "status"], name="notificatio_user_id_8ab96f_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["business", "-updated_at"], name="notificatio_busines_36537d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["notification_type"], name="notificatio_notific_19df93_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["business", "-updated_at"], name="orders_busines_57543a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "-updated_at"], name="orders_custome_7a443f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="orders_status_762191_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["order_number"], name="orders_order_n_1336be_idx"),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(
                fields=["business", "-updated_at"], name="deliveries_busines_4e7137_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(
                fields=["delivery_person", "status"], name="deliveries_deliver_26565b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(fields=["status"], name="deliveries_status_c2a7cc_idx"),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(fields=["customer"], name="deliveries_custome_3857bc_idx"),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["email", "purpose", "otp_type", "-created_at"], name="otps_email_93e407_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["phone_number", "purpose", "otp_type", "-created_at"],
                name="otps_phone_n_552fa3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(fields=["otp_code", "verified"], name="otps_otp_cod_8f58b9_idx"),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(fields=["expires_at"], name="otps_expires_f6308f_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(fields=["token", "used"], name="password_re_token_69d40c_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(fields=["code", "used"], name="password_re_code_7a5d57_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["email", "reset_type", "-updated_at"], name="password_re_email_ee3273_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["phone_number", "reset_type", "-updated_at"],
                name="password_re_phone_n_1641fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(fields=["expires_at"], name="password_re_expires_8e96b7_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order"], name="order_items_order_i_26ad88_idx"),
        ),
        migrations.AddIndex(
            model_name="invoiceline",
            index=models.Index(fields=["invoice"], name="invoice_lin_invoice_019757_idx"),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(fields=["user", "device_id"], name="refresh_tok_user_id_89b362_idx"),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(fields=["token"], name="refresh_tok_token_e21bac_idx"),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(fields=["expires_at"], name="refresh_tok_expires_a128d9_idx"),
        ),
        migrations.AddIndex(
            model_name="salary",
            index=models.Index(fields=["business", "user"], name="salaries_busines_ed2fdc_idx"),
        ),
        migrations.AddIndex(
            model_name="salary",
            index=models.Index(
                fields=["effective_from", "effective_to"], name="salaries_effecti_97e442_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payroll",
            index=models.Index(
                fields=["business", "-updated_at"], name="payrolls_busines_c5b8f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payroll",
            index=models.Index(fields=["user", "-updated_at"], name="payrolls_user_id_54465f_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["user", "-start_time"], name="sessions_user_id_19be98_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["device_id"], name="sessions_device__73081a_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["business", "-updated_at"], name="stock_movem_busines_fbc579_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["product", "-updated_at"], name="stock_movem_product_9ab8bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["movement_type"], name="stock_movem_movemen_d922c9_idx"),
        ),
        migrations.AddIndex(
            model_name="subcategory",
            index=models.Index(
                fields=["business", "category"], name="subcategori_busines_fd1d55_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subcategory",
            unique_together={("business", "category", "name")},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["business", "name"], name="products_busines_387713_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["barcode"], name="products_barcode_d008ac_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category"], name="products_categor_4083ff_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_expired"], name="products_is_expi_016a7d_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["quantity"], name="products_quantit_a80737_idx"),
        ),
    ]
