# Generated by Django 5.2.8 on 2025-11-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("verification", "Verification"),
                    ("signup", "Signup"),
                    ("login", "Login"),
                    ("password_reset", "Password Reset"),
                    ("email_verification", "Email Verification"),
                    ("phone_verification", "Phone Verification"),
                ],
                default="verification",
                max_length=50,
            ),
        ),
    ]
