# Generated by Django 5.2.8 on 2025-11-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0002_simplify_otp_purpose"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="otp",
            name="otps_email_93e407_idx",
        ),
        migrations.RemoveIndex(
            model_name="otp",
            name="otps_phone_n_552fa3_idx",
        ),
        migrations.RemoveField(
            model_name="otp",
            name="purpose",
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["email", "otp_type", "-created_at"], name="otps_email_e6dfca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["phone_number", "otp_type", "-created_at"], name="otps_phone_n_d30cc8_idx"
            ),
        ),
    ]
