# Generated by Django 5.2.8 on 2025-11-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0003_remove_otp_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailpulseuser",
            name="email_verified",
            field=models.BooleanField(default=False, help_text="Email/phone verification status"),
        ),
        migrations.AlterField(
            model_name="retailpulseuser",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Account status (can be disabled by admin)"
            ),
        ),
    ]
