# Generated by Django 5.2.8 on 2025-11-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0004_add_email_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailpulseuser",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Account status"),
        ),
    ]
