# Generated by Django 5.2.8 on 2025-11-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0005_alter_retailpulseuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailpulseuser",
            name="google_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Google OAuth user ID (sub from Google)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
