# Generated by Django 5.2.8 on 2025-11-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0006_add_google_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailpulseuser",
            name="google_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Google OAuth user ID",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
