# Generated by Django 5.2.8 on 2025-11-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0007_alter_retailpulseuser_google_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="token",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="passwordresettoken",
            unique_together={
                ("email", "reset_type", "token"),
                ("phone_number", "reset_type", "code"),
            },
        ),
    ]
