# Generated by Django 5.2.8 on 2025-11-18 09:51

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0008_alter_passwordresettoken_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[("REGULAR", "Regular"), ("WHOLESALER", "Wholesaler")],
                default="REGULAR",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15),
                ),
                ("due_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("OVERDUE", "Overdue"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("SETTLED", "Settled"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="persistence_models.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_credits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="persistence_models.customer",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credits",
                        to="persistence_models.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit",
                "verbose_name_plural": "Credits",
                "db_table": "credits",
            },
        ),
        migrations.CreateModel(
            name="CreditPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("payment_date", models.DateTimeField()),
                ("payment_method", models.CharField(default="cash", max_length=30)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_credit_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="persistence_models.credit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Payment",
                "verbose_name_plural": "Credit Payments",
                "db_table": "credit_payments",
            },
        ),
        migrations.AddIndex(
            model_name="credit",
            index=models.Index(fields=["business", "customer"], name="credits_busines_d3cef6_idx"),
        ),
        migrations.AddIndex(
            model_name="credit",
            index=models.Index(fields=["status"], name="credits_status_815afb_idx"),
        ),
        migrations.AddIndex(
            model_name="credit",
            index=models.Index(fields=["due_date"], name="credits_due_dat_6772f7_idx"),
        ),
        migrations.AddIndex(
            model_name="credit",
            index=models.Index(fields=["business", "status"], name="credits_busines_19ade0_idx"),
        ),
        migrations.AddIndex(
            model_name="creditpayment",
            index=models.Index(
                fields=["credit", "-payment_date"], name="credit_paym_credit__bb2015_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditpayment",
            index=models.Index(fields=["payment_date"], name="credit_paym_payment_8e45cb_idx"),
        ),
    ]
