# Generated by Django 5.2.8 on 2025-11-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0009_customer_customer_type_credit_creditpayment_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="subcategory",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("business", "name"), name="uniq_category_business_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subcategory__isnull", True)),
                fields=("business", "category", "name"),
                name="uniq_product_category_name_when_no_subcategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subcategory__isnull", False)),
                fields=("business", "subcategory", "name"),
                name="uniq_product_subcategory_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="subcategory",
            constraint=models.UniqueConstraint(
                fields=("category", "name"), name="uniq_subcategory_per_category"
            ),
        ),
    ]
