# Generated by Django 5.2.8 on 2025-11-22 17:45

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0010_alter_category_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("UPDATED", "Updated"),
                            ("PAYMENT_RECEIVED", "Payment Received"),
                            ("REFUNDED", "Refunded"),
                            ("CANCELLED", "Cancelled"),
                            ("LINE_ADDED", "Line Added"),
                            ("LINE_REMOVED", "Line Removed"),
                            ("LINE_UPDATED", "Line Updated"),
                            ("CREDIT_APPLIED", "Credit Applied"),
                            ("STATUS_CHANGED", "Status Changed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoice_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="persistence_models.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Log",
                "verbose_name_plural": "Invoice Logs",
                "db_table": "invoice_logs",
                "indexes": [
                    models.Index(
                        fields=["invoice", "-created_at"], name="invoice_log_invoice_059ff8_idx"
                    ),
                    models.Index(fields=["action"], name="invoice_log_action_6dce3a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="InvoicePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("mobile_money", "Mobile Money"),
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("credit", "Credit"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "change_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount returned to customer (overpayment)",
                        max_digits=15,
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount refunded to customer",
                        max_digits=15,
                    ),
                ),
                ("payment_date", models.DateTimeField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoice_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="persistence_models.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Payment",
                "verbose_name_plural": "Invoice Payments",
                "db_table": "invoice_payments",
                "indexes": [
                    models.Index(
                        fields=["invoice", "-payment_date"], name="invoice_pay_invoice_d9632d_idx"
                    ),
                    models.Index(fields=["payment_date"], name="invoice_pay_payment_de7f11_idx"),
                ],
            },
        ),
    ]
