# Generated by Django 5.2.8 on 2025-11-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0011_invoicelog_invoicepayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicepayment",
            name="idempotency_key",
            field=models.UUIDField(
                blank=True,
                help_text="Prevents double-spending if payment is retried",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="invoicepayment",
            index=models.Index(fields=["idempotency_key"], name="invoice_pay_idempot_431d3c_idx"),
        ),
    ]
