# Generated by Django 5.2.8 on 2025-11-24 15:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0012_invoicepayment_idempotency_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("UPDATED", "Updated"),
                            ("APPROVED", "Approved"),
                            ("DELETED", "Deleted"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount_before",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
                ),
                (
                    "amount_after",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
                ),
                ("reason_before", models.TextField(blank=True, null=True)),
                ("reason_after", models.TextField(blank=True, null=True)),
                ("reason_details_before", models.TextField(blank=True, null=True)),
                ("reason_details_after", models.TextField(blank=True, null=True)),
                (
                    "payment_method_before",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CASH", "Cash"),
                            ("MOBILE_MONEY", "Mobile money"),
                            ("BANK_TRANSFER", "Bank transfer"),
                            ("CARD", "Card"),
                            ("CHECK", "Check"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "payment_method_after",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CASH", "Cash"),
                            ("MOBILE_MONEY", "Mobile money"),
                            ("BANK_TRANSFER", "Bank transfer"),
                            ("CARD", "Card"),
                            ("CHECK", "Check"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "payee_type_before",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EMPLOYEE", "Employee"),
                            ("SUPPLIER", "Supplier"),
                            ("SERVICE_PROVIDER", "Service provider"),
                            ("GOVERNMENT", "Government"),
                            ("LANDLORD", "Landlord"),
                            ("OTHER", "Other"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "payee_type_after",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EMPLOYEE", "Employee"),
                            ("SUPPLIER", "Supplier"),
                            ("SERVICE_PROVIDER", "Service provider"),
                            ("GOVERNMENT", "Government"),
                            ("LANDLORD", "Landlord"),
                            ("OTHER", "Other"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("payee_name_before", models.CharField(blank=True, max_length=255, null=True)),
                ("payee_name_after", models.CharField(blank=True, max_length=255, null=True)),
                ("justification_snapshot", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Expense Audit Log",
                "verbose_name_plural": "Expense Audit Logs",
                "db_table": "expense_audit_logs",
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="justification_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="expense",
            name="payee_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="expense",
            name="payee_type",
            field=models.CharField(
                choices=[
                    ("EMPLOYEE", "Employee"),
                    ("SUPPLIER", "Supplier"),
                    ("SERVICE_PROVIDER", "Service provider"),
                    ("GOVERNMENT", "Government"),
                    ("LANDLORD", "Landlord"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("MOBILE_MONEY", "Mobile money"),
                    ("BANK_TRANSFER", "Bank transfer"),
                    ("CARD", "Card"),
                    ("CHECK", "Check"),
                    ("OTHER", "Other"),
                ],
                default="CASH",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="expense",
            name="reason_details",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="expense_type",
            field=models.CharField(
                choices=[
                    ("REPLENISHMENT", "Replenishment"),
                    ("MISCELLANEOUS", "Miscellaneous"),
                    ("ELECTRICITY", "Electricity Bill"),
                    ("WATER", "Water Bill"),
                    ("SALARY", "Salary"),
                    ("EXTRA", "Extra"),
                    ("MAINTENANCE", "Maintenance"),
                    ("TAX", "Tax"),
                    ("RENT", "Rent"),
                    ("MARKETING", "Marketing"),
                    ("INSURANCE", "Insurance"),
                    ("TRANSPORT", "Transport"),
                    ("UTILITIES", "Utilities"),
                    ("OFFICE_SUPPLIES", "Office Supplies"),
                    ("PROFESSIONAL_SERVICES", "Professional Services"),
                ],
                max_length=25,
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["payment_method"], name="expenses_payment_b96059_idx"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["payee_type"], name="expenses_payee_t_55dadd_idx"),
        ),
        migrations.AddField(
            model_name="expenseauditlog",
            name="expense",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="persistence_models.expense",
            ),
        ),
        migrations.AddField(
            model_name="expenseauditlog",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expense_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="expenseauditlog",
            index=models.Index(
                fields=["expense", "-created_at"], name="expense_aud_expense_bd060d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expenseauditlog",
            index=models.Index(fields=["action"], name="expense_aud_action_92d7d5_idx"),
        ),
    ]
