# Generated by Django 5.2.8 on 2025-11-25 17:33

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0014_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="discount",
        ),
        migrations.AddField(
            model_name="invoice",
            name="total_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total discount from all product lines",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="currency",
            field=models.CharField(default="Fcfa", max_length=10),
        ),
    ]
