# Generated by Django 5.2.8 on 2025-11-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0015_remove_invoice_discount_invoice_total_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the invoice has been archived instead of deleted",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["business", "is_archived", "-updated_at"],
                name="invoices_busines_ce371b_idx",
            ),
        ),
    ]
