# Generated by Django 5.2.8 on 2025-11-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0016_invoice_is_archived_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("CREDIT", "Credit"),
                ],
                max_length=20,
            ),
        ),
    ]
