# Generated by Django 5.2.8 on 2025-11-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0017_alter_invoice_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
