# Generated by Django 5.2.8 on 2025-12-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0018_alter_invoice_due_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="business",
            unique_together={("owner", "name")},
        ),
    ]
