# Generated by Django 5.2.8 on 2025-12-06 15:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0019_alter_business_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentationCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("username", models.CharField(db_index=True, max_length=150, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Documentation Credential",
                "verbose_name_plural": "Documentation Credentials",
                "db_table": "documentation_credentials",
                "indexes": [
                    models.Index(fields=["username"], name="documentati_usernam_c11cdb_idx"),
                    models.Index(fields=["expires_at"], name="documentati_expires_671dc0_idx"),
                    models.Index(
                        fields=["is_active", "expires_at"], name="documentati_is_acti_f58519_idx"
                    ),
                ],
            },
        ),
    ]
