# Generated by Django 5.2.8 on 2025-12-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0020_add_documentation_credential"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="format",
            field=models.CharField(choices=[("pdf", "PDF")], default="pdf", max_length=10),
        ),
    ]
