# Generated by Django 5.2.8 on 2025-12-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0021_alter_report_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="format",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("word", "Word")], default="pdf", max_length=10
            ),
        ),
    ]
