# Generated by Django 5.2.8 on 2025-12-27 16:17

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence_models", "0022_alter_report_format"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("suspended", "Suspended"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                (
                    "billing_period",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annual", "Annual")],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("trial_end_date", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                (
                    "external_subscription_id",
                    models.CharField(
                        blank=True,
                        help_text="External subscription ID (e.g., Stripe subscription ID)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        db_column="business_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="persistence_models.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "db_table": "subscriptions",
            },
        ),
        migrations.AddField(
            model_name="business",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                db_column="subscription_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businesses",
                to="persistence_models.subscription",
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., 'basic', 'pro'", max_length=50, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly subscription price",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "annual_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual subscription price",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON field for plan features (e.g., max_users, max_products)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "db_table": "subscription_plans",
                "indexes": [
                    models.Index(fields=["code"], name="subscriptio_code_e250fc_idx"),
                    models.Index(
                        fields=["is_active"], name="subscriptio_is_acti_4d4352_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                db_column="plan_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="persistence_models.subscriptionplan",
            ),
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("mtn_mobile_money", "MTN Mobile Money"),
                            ("orange_mobile_money", "Orange Mobile Money"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="XAF", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "external_transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="External transaction ID (e.g., Stripe payment intent ID, Mobile Money transaction ID)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON field for provider-specific response data",
                    ),
                ),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("initiated_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "idempotency_key",
                    models.UUIDField(
                        blank=True,
                        help_text="Prevents duplicate payments if payment is retried",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        db_column="subscription_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="persistence_models.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
                "db_table": "payment_transactions",
                "indexes": [
                    models.Index(
                        fields=["subscription", "-created_at"],
                        name="payment_tra_subscri_ae79bd_idx",
                    ),
                    models.Index(
                        fields=["status"], name="payment_tra_status_137fde_idx"
                    ),
                    models.Index(
                        fields=["provider"], name="payment_tra_provide_90035f_idx"
                    ),
                    models.Index(
                        fields=["external_transaction_id"],
                        name="payment_tra_externa_a7becb_idx",
                    ),
                    models.Index(
                        fields=["idempotency_key"],
                        name="payment_tra_idempot_6c5e42_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["business", "-created_at"],
                name="subscriptio_busines_4eb8fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["status"], name="subscriptio_status_572d44_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["external_subscription_id"],
                name="subscriptio_externa_6e617b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["end_date"], name="subscriptio_end_dat_763002_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["trial_end_date"], name="subscriptio_trial_e_33d307_idx"
            ),
        ),
    ]
