# Generated by Django 5.2.8 on 2025-12-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "persistence_models",
            "0023_subscription_business_subscription_subscriptionplan_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
